name: rick_and_morty
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # state management
  provider: ^6.0.5

  # ui
  adaptive_theme: ^3.1.1
  custom_sliding_segmented_control: ^1.7.4
  sliver_tools: ^0.2.9
  extended_nested_scroll_view: ^6.0.0
  fade_shimmer: ^2.2.0
  flutter_staggered_grid_view: ^0.6.2

  # api
  dartz: ^0.10.1
  dio: ^4.0.6
  universal_internet_checker: ^0.1.2
  retrofit: ^3.3.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  # logger
  talker_dio_logger: ^1.0.3
  ansicolor: ^2.0.1

  # navigation
  auto_route: ^5.0.4

  # di
  get_it: ^7.2.0

  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  retrofit_generator: ^4.2.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  auto_route_generator: ^5.0.3

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
